---
- hosts: localhost
  vars:
  - warName: helloworld.war
  - warRemotePath: /usr/share/tomcat/webapps

  tasks:
  - name: Download WAR to server
    command: wget http://example.com/file.war -O {{ warRemotePath }}/{{ warName }}
    notify:
        - restart tomcat7
        
  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
